### ISSUE TITLE
I1 User Epic: "Gaming Domain"

### ISSUE THREAD

**Issue by vanhoofa3995** [vanhoofa3995/CSC-289-Digital-Crafter-Project#1]
As a user, I want to able to create an account, login, and be able to buy or sell games and items through the app.
- [x] Create a user account
- [x] Login to a user account
- [x] Browse a list of games and items
- [x] Add items to a shopping cart
- [x] View the selected items in a shopping cart
- [x] Go to checkout with the shopping cart
- [x] Purchase the selected shopping cart items
- [x] Receive an order confirmation
